import { formatAutoexecBanner } from '@workspace/cs2/autoexec/compose/autoexec-banner';
import { formatBindBody } from '@workspace/cs2/binds/export/format-cfg';
import type { BindEntry } from '@workspace/cs2/binds/model/types';
import { formatConfigBody } from '@workspace/cs2/config/export/format-config-cfg';
import type { ConfigSettings } from '@workspace/cs2/config/model/types';
import { crosshairSettingsToConsoleLines } from '@workspace/cs2/crosshair/export/crosshair-console-commands';
import type { CrosshairSettings } from '@workspace/cs2/crosshair/model/types';
import { encodeShareCode } from '@workspace/cs2/crosshair/share-code/encode-share-code';

export type AutoexecSectionId = 'crosshair' | 'config' | 'binds';
export type AutoexecToggleId = AutoexecSectionId | 'banner';

export interface AutoexecSource {
  binds: BindEntry[];
  config: ConfigSettings;
  crosshair: CrosshairSettings;
}

export type AutoexecInclude = Record<AutoexecToggleId, boolean>;

const CFG_PATH =
  '// Drop in ...\\Steam\\steamapps\\common\\Counter-Strike Global Offensive\\game\\csgo\\cfg\\autoexec.cfg';

function safeShareCode(crosshair: CrosshairSettings): string {
  try {
    return encodeShareCode(crosshair);
  } catch {
    return 'unavailable';
  }
}

function crosshairSection(crosshair: CrosshairSettings): string[] {
  return [
    '// ===== crosshair =====',
    ...crosshairSettingsToConsoleLines(crosshair),
    `// share code: ${safeShareCode(crosshair)}`,
    '',
  ];
}

function configSection(config: ConfigSettings): string[] {
  return ['// ===== config =====', ...formatConfigBody(config), ''];
}

function bindsSection(binds: BindEntry[]): string[] {
  return ['// ===== binds =====', ...formatBindBody(binds), ''];
}

export function composeAutoexec(
  source: AutoexecSource,
  include: AutoexecInclude
): string {
  const lines: string[] = [
    '// autoexec.cfg',
    '// Generated by bindr.lol',
    CFG_PATH,
    '',
  ];

  if (include.crosshair) {
    lines.push(...crosshairSection(source.crosshair));
  }

  if (include.config) {
    lines.push(...configSection(source.config));
  }

  if (include.binds) {
    lines.push(...bindsSection(source.binds));
  }

  lines.push('host_writeconfig');
  lines.push('');

  if (include.banner) {
    lines.push(...formatAutoexecBanner());
  } else {
    lines.push('echo "bindr.lol autoexec loaded"');
  }
  lines.push('');

  return lines.join('\n');
}
