import { formatBindLines } from '@/features/binds/lib/export/format-bind';
import type { BindEntry } from '@/features/binds/lib/model/types';

export function formatBindCfg(binds: BindEntry[]): string {
  if (binds.length === 0) {
    return '// No binds configured\n';
  }

  return [
    '// Generated by Bindr — paste into autoexec.cfg or run in console',
    formatBindLines(binds),
    '',
  ].join('\n');
}
