import { formatBindLines } from '@/features/binds/lib/export/format-bind';
import { formatBindCfgNotes } from '@/features/binds/lib/export/format-cfg-notes';
import {
  BIND_CATEGORY_LABELS,
  BIND_CATEGORY_ORDER,
} from '@/features/binds/lib/model/recommended-binds';
import type { BindCategory, BindEntry } from '@/features/binds/lib/model/types';

function groupBindsByCategory(binds: BindEntry[]) {
  const grouped = new Map<BindCategory | 'other', BindEntry[]>();

  for (const bind of binds) {
    const bucket = bind.category ?? 'other';
    const current = grouped.get(bucket) ?? [];
    current.push(bind);
    grouped.set(bucket, current);
  }

  return grouped;
}

export function formatBindCfg(binds: BindEntry[]): string {
  if (binds.length === 0) {
    return '// No binds configured\n';
  }

  const grouped = groupBindsByCategory(binds);
  const sections: string[] = [
    '// Generated by Bindr — paste into autoexec.cfg or run in console',
    '',
  ];

  for (const category of BIND_CATEGORY_ORDER) {
    const categoryBinds = grouped.get(category);
    if (!categoryBinds?.length) {
      continue;
    }

    sections.push(`// ${BIND_CATEGORY_LABELS[category]}`);
    sections.push(formatBindLines(categoryBinds));
    sections.push('');
  }

  const uncategorized = grouped.get('other');
  if (uncategorized?.length) {
    sections.push('// Custom');
    sections.push(formatBindLines(uncategorized));
    sections.push('');
  }

  sections.push(formatBindCfgNotes().trimEnd());

  return `${sections.join('\n')}\n`;
}
