import type { ConfigSettings } from '@/features/config/lib/model/types';

function formatNumber(value: number) {
  return String(value);
}

function formatBool(value: boolean) {
  return value ? '1' : '0';
}

export function formatViewmodelLines(viewmodel: ConfigSettings['viewmodel']) {
  const lines = [
    `viewmodel_fov ${formatNumber(viewmodel.fov)}`,
    `viewmodel_offset_x ${formatNumber(viewmodel.offsetX)}`,
    `viewmodel_offset_y ${formatNumber(viewmodel.offsetY)}`,
    `viewmodel_offset_z ${formatNumber(viewmodel.offsetZ)}`,
  ];

  if (viewmodel.presetPos === 0) {
    lines.push(`viewmodel_presetpos ${viewmodel.presetPos}`);
  }

  return lines;
}

export function formatRadarLines(radar: ConfigSettings['radar']) {
  return [
    `cl_radar_scale ${formatNumber(radar.scale)}`,
    `cl_hud_radar_scale ${formatNumber(radar.hudScale)}`,
    `cl_radar_always_centered ${formatBool(radar.alwaysCentered)}`,
    `cl_radar_rotate ${formatBool(radar.rotate)}`,
    `cl_radar_icon_scale_min ${formatNumber(radar.iconScaleMin)}`,
    `cl_radar_square_with_scoreboard ${formatBool(radar.squareWithScoreboard)}`,
  ];
}

export function formatNetworkLines(network: ConfigSettings['network']) {
  return [
    `rate ${network.rate}`,
    `cl_interp_ratio ${network.interpRatio}`,
    `cl_interp ${formatNumber(network.interp)}`,
    `cl_cmdrate ${network.cmdrate}`,
    `cl_updaterate ${network.updaterate}`,
    `mm_dedicated_search_maxping ${network.maxPing}`,
  ];
}

export function formatPerformanceLines(
  performance: ConfigSettings['performance']
) {
  const lines = [
    `fps_max ${performance.fpsMax}`,
    `fps_max_ui ${performance.fpsMaxUi}`,
    `r_drawtracers_firstperson ${formatBool(performance.drawTracersFirstPerson)}`,
    `cl_autohelp ${formatBool(performance.autohelp)}`,
    `gameinstructor_enable ${formatBool(performance.gameInstructor)}`,
    `cl_showhelp ${formatBool(performance.showHelp)}`,
    `cl_disablefreezecam ${formatBool(performance.disableFreezeCam)}`,
  ];

  if (performance.lowLatencySleep) {
    lines.push('engine_low_latency_sleep_after_client_tick true');
  }

  return lines;
}

export function formatConfigCfg(config: ConfigSettings) {
  return [
    '// Generated by Bindr',
    '// config',
    '',
    '// viewmodel',
    ...formatViewmodelLines(config.viewmodel),
    '',
    '// radar',
    ...formatRadarLines(config.radar),
    '',
    '// network',
    ...formatNetworkLines(config.network),
    '',
    '// performance',
    ...formatPerformanceLines(config.performance),
    '',
  ].join('\n');
}
