import type { ViewmodelSettings } from '@/features/config/lib/model/types';

function formatViewmodelValue(value: number) {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}

export function formatViewmodelLines(viewmodel: ViewmodelSettings) {
  return [
    `viewmodel_fov ${formatViewmodelValue(viewmodel.fov)}`,
    `viewmodel_offset_x ${formatViewmodelValue(viewmodel.offsetX)}`,
    `viewmodel_offset_y ${formatViewmodelValue(viewmodel.offsetY)}`,
    `viewmodel_offset_z ${formatViewmodelValue(viewmodel.offsetZ)}`,
  ];
}

export function formatConfigCfg(viewmodel: ViewmodelSettings) {
  return [
    '// Generated by Bindr',
    '// config',
    ...formatViewmodelLines(viewmodel),
    '',
  ].join('\n');
}
