import type { ConfigSettings } from '@/features/config/lib/model/types';

function formatNumber(value: number) {
  return String(value);
}

function formatBool(value: boolean) {
  return value ? '1' : '0';
}

export function formatViewmodelLines(viewmodel: ConfigSettings['viewmodel']) {
  const lines = [
    `viewmodel_fov ${formatNumber(viewmodel.fov)}`,
    `viewmodel_offset_x ${formatNumber(viewmodel.offsetX)}`,
    `viewmodel_offset_y ${formatNumber(viewmodel.offsetY)}`,
    `viewmodel_offset_z ${formatNumber(viewmodel.offsetZ)}`,
    `cl_righthand ${formatBool(viewmodel.rightHand)}`,
    `cl_bobamt_lat ${formatNumber(viewmodel.bobLat)}`,
    `cl_bobamt_vert ${formatNumber(viewmodel.bobVert)}`,
    `cl_bob_lower_amt ${formatNumber(viewmodel.bobLowerAmt)}`,
  ];

  if (viewmodel.presetPos === 0) {
    lines.push(`viewmodel_presetpos ${viewmodel.presetPos}`);
  }

  return lines;
}

export function formatMouseLines(mouse: ConfigSettings['mouse']) {
  return [
    `sensitivity ${formatNumber(mouse.sensitivity)}`,
    `zoom_sensitivity_ratio ${formatNumber(mouse.zoomSensitivityRatio)}`,
    `m_rawinput ${formatBool(mouse.rawInput)}`,
  ];
}

export function formatRadarLines(radar: ConfigSettings['radar']) {
  return [
    `cl_radar_scale ${formatNumber(radar.scale)}`,
    `cl_hud_radar_scale ${formatNumber(radar.hudScale)}`,
    `cl_radar_always_centered ${formatBool(radar.alwaysCentered)}`,
    `cl_radar_rotate ${formatBool(radar.rotate)}`,
    `cl_radar_icon_scale_min ${formatNumber(radar.iconScaleMin)}`,
    `cl_radar_square_with_scoreboard ${formatBool(radar.squareWithScoreboard)}`,
  ];
}

export function formatNetworkLines(network: ConfigSettings['network']) {
  return [
    `rate ${network.rate}`,
    `cl_interp_ratio ${network.interpRatio}`,
    `cl_interp ${formatNumber(network.interp)}`,
    `cl_cmdrate ${network.cmdrate}`,
    `cl_updaterate ${network.updaterate}`,
    `mm_dedicated_search_maxping ${network.maxPing}`,
  ];
}

export function formatAudioLines(audio: ConfigSettings['audio']) {
  return [
    `volume ${formatNumber(audio.master)}`,
    `voice_scale ${formatNumber(audio.voiceScale)}`,
    `snd_mute_losefocus ${formatBool(audio.muteOnFocusLoss)}`,
    `snd_roundstart_volume ${formatNumber(audio.musicVolume)}`,
    `snd_roundend_volume ${formatNumber(audio.musicVolume)}`,
    `snd_mvp_volume ${formatNumber(audio.musicVolume)}`,
    `snd_menumusic_volume ${formatNumber(audio.musicVolume)}`,
    `snd_deathcamera_volume ${formatNumber(audio.musicVolume)}`,
    `snd_tensecondwarning_volume ${formatNumber(audio.tenSecondWarning)}`,
  ];
}

export function formatPerformanceLines(
  performance: ConfigSettings['performance']
) {
  const lines = [
    `fps_max ${performance.fpsMax}`,
    `fps_max_ui ${performance.fpsMaxUi}`,
    `r_drawtracers_firstperson ${formatBool(performance.drawTracersFirstPerson)}`,
    `r_dynamic ${formatBool(performance.dynamicLight)}`,
    `mat_queue_mode ${performance.multicore ? '2' : '-1'}`,
    `cl_forcepreload ${formatBool(performance.forcePreload)}`,
    `cl_animate_player_models ${formatBool(performance.animatePlayerModels)}`,
    `mat_disable_bloom ${formatBool(performance.disableBloom)}`,
    `cl_autohelp ${formatBool(performance.autohelp)}`,
    `gameinstructor_enable ${formatBool(performance.gameInstructor)}`,
    `cl_showhelp ${formatBool(performance.showHelp)}`,
    `cl_disablefreezecam ${formatBool(performance.disableFreezeCam)}`,
  ];

  if (performance.lowLatencySleep) {
    lines.push('engine_low_latency_sleep_after_client_tick true');
  }

  return lines;
}

export function formatHudLines(hud: ConfigSettings['hud']) {
  return [
    `cl_hud_color ${hud.hudColor}`,
    `hud_scaling ${formatNumber(hud.hudScaling)}`,
    `cl_teammate_colors_show ${hud.teammateColors}`,
    `cl_hud_healthammo_style ${hud.healthAmmoStyle}`,
    `cl_showloadout ${formatBool(hud.showLoadout)}`,
    `cl_hud_bomb_under_radar ${formatBool(hud.bombUnderRadar)}`,
    `cl_teamid_overhead_fade_near_crosshair ${formatNumber(hud.teamidOverheadFadeNearCrosshair)}`,
    `r_show_build_info ${hud.showBuildInfo}`,
  ];
}

export function formatConfigBody(config: ConfigSettings): string[] {
  return [
    '// viewmodel',
    ...formatViewmodelLines(config.viewmodel),
    '',
    '// mouse',
    ...formatMouseLines(config.mouse),
    '',
    '// radar',
    ...formatRadarLines(config.radar),
    '',
    '// network',
    ...formatNetworkLines(config.network),
    '',
    '// audio',
    ...formatAudioLines(config.audio),
    '',
    '// performance',
    ...formatPerformanceLines(config.performance),
    '',
    '// hud',
    ...formatHudLines(config.hud),
  ];
}

export function formatConfigCfg(config: ConfigSettings) {
  return [
    '// Generated by Bindr',
    '// config',
    '',
    ...formatConfigBody(config),
    '',
  ].join('\n');
}
