import type { CrosshairSettings } from '@/features/crosshair/lib/model/types';

export const DEFAULT_CROSSHAIR: CrosshairSettings = {
  gap: -2,
  outline: 1,
  red: 50,
  green: 255,
  blue: 50,
  alpha: 255,
  splitDistance: 7,
  followRecoil: false,
  fixedCrosshairGap: 3,
  color: 5,
  outlineEnabled: true,
  innerSplitAlpha: 1,
  outerSplitAlpha: 0.5,
  splitSizeRatio: 0.3,
  thickness: 1,
  centerDotEnabled: false,
  deployedWeaponGapEnabled: false,
  alphaEnabled: true,
  tStyleEnabled: false,
  style: 4,
  length: 1,
};
